//
//  CardOnFileBuilder.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/27.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import CleanSwiftUtil
import FinanceEntity

// MARK: - CardOnFileBuilder

final class CardOnFileBuilder: Builder<CardOnFileDependency> {

}

// MARK: - CardOnFileBuildingLogic

extension CardOnFileBuilder: CardOnFileBuildingLogic {
    
    func build(listener: CardOnFileListener, paymentMethods: [PaymentMethod]) -> Destination {
        let component = CardOnFileComponent(dependency: dependency)
        let viewController = CardOnFileViewController()
        let interactor = CardOnFileInteractor(worker: CardOnFileWorker(), paymentMethods: paymentMethods)
        let presenter = CardOnFilePresenter()
        let router = CardOnFileRouter(viewController: viewController)
        viewController.interactor = interactor
        interactor.router = router
        interactor.presenter = presenter
        interactor.listener = listener
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - CardOnFileBuildingLogic definition

protocol CardOnFileBuildingLogic: Buildable {
    typealias Destination = CardOnFileViewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build(listener: CardOnFileListener, paymentMethods: [PaymentMethod]) -> Destination
}

// MARK: - CardOnFileDependency

protocol CardOnFileDependency: CleanSwiftDependency {
    // TODO: Declare the set of dependencies required by this RIB, but cannot be
    // created by this RIB.
}

// MARK: - CardOnFileComponent

final class CardOnFileComponent: CleanSwiftComponent<CardOnFileDependency> {

    // TODO: Declare 'fileprivate' dependencies that are only used by this RIB.
}
