//
//  SuperPayDashboardPresenter.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/27.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FoundationExt

// MARK: - SuperPayDashboardPresenter

final class SuperPayDashboardPresenter {
    weak var viewController: SuperPayDashboardDisplayLogic?
}

// MARK: - SuperPayDashboardPresentationLogic

extension SuperPayDashboardPresenter: SuperPayDashboardPresentationLogic {
    
    func present(_ response: SuperPayDashboard.Response) {
        switch response {
        case let .balance(amount):
            if let value = Formatter.balanceFormatter.string(from: NSNumber(value: amount)) {
                viewController?.display(SuperPayDashboard.ViewModel.Balance(amount: value))
            }
        }
    }
}

// MARK: - SuperPayDashboardDisplayLogic definition

protocol SuperPayDashboardDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: SuperPayDashboard.ViewModel.Balance)
}
