//
//  SuperPayDashboardWorker.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/27.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - SuperPayDashboardWorker

final class SuperPayDashboardWorker  {

}

// MARK: - SuperPayDashboardWorkingLogic

extension SuperPayDashboardWorker: SuperPayDashboardWorkingLogic {
    
    func doSomeWork() {
        
    }
}
