//
//  CardOnFileDashboardPresenter.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/27.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - CardOnFileDashboardPresenter

final class CardOnFileDashboardPresenter {
    weak var viewController: CardOnFileDashboardDisplayLogic?
}

// MARK: - CardOnFileDashboardPresentationLogic

extension CardOnFileDashboardPresenter: CardOnFileDashboardPresentationLogic {
    func present(_ response: CardOnFileDashboard.Response) {
        switch response {
        case let .list(items):
            let viewModel = CardOnFileDashboard.ViewModel.List(items: items.map { .init($0) })
            viewController?.display(viewModel)
        }
    }
}

// MARK: - CardOnFileDashboardDisplayLogic definition

protocol CardOnFileDashboardDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: CardOnFileDashboard.ViewModel.List)
}
