//
//  CardOnFileDashboardBuilder.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/27.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import CleanSwiftUtil
import FinanceRepository

// MARK: - CardOnFileDashboardBuilder

final class CardOnFileDashboardBuilder: Builder<CardOnFileDashboardDependency> {

}

// MARK: - CardOnFileDashboardBuildingLogic

extension CardOnFileDashboardBuilder: CardOnFileDashboardBuildingLogic {
    func build(withListener listener: CardOnFileDashboardListener) -> Destination {
        let component = CardOnFileDashboardComponent(dependency: dependency)
        let viewController = CardOnFileDashboardViewController()
        let interactor = CardOnFileDashboardInteractor(
            worker: CardOnFileDashboardWorker(),
            listener: listener,
            dependency: component
        )
        let presenter = CardOnFileDashboardPresenter()
        let router = CardOnFileDashboardRouter(viewController: viewController)
        viewController.interactor = interactor
        interactor.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - CardOnFileDashboardBuildingLogic definition

protocol CardOnFileDashboardBuildingLogic {
    typealias Destination = CardOnFileDashboardViewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build(withListener listener: CardOnFileDashboardListener) -> Destination
}

// MARK: - CardOnFileDashboardDependency

protocol CardOnFileDashboardDependency: Dependency {
    var cardOnFileRepository: CardOnFileRepositoryAvailable { get }
}

// MARK: - CardOnFileDashboardComponent

final class CardOnFileDashboardComponent: Component<CardOnFileDashboardDependency>, CardOnFileDashboardInteractorDependency{
    var cardOnFileRepository: CardOnFileRepositoryAvailable { dependency.cardOnFileRepository }
}
