//
//  CardOnFileDashboardModels.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/27.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import FinanceEntity

enum CardOnFileDashboard {

    enum Request {
        struct OnLoad {}
        struct OnAdd {}
    }
    
    enum Response: Equatable {
        case list(items: [PaymentMethod])
    }
    
    enum ViewModel {
        struct List {
            let items: [Item]
        }
        
        struct Item {
            let name: String
            let digits: String
            let color: UIColor

            init(_ paymentMethod: PaymentMethod) {
                name = paymentMethod.name
                digits = "**** \(paymentMethod.digits)"
                color = UIColor(hex: paymentMethod.color) ?? .systemGray2
            }
        }
    }
}
