//
//  TransportHomePresenter.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/28.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import FoundationExt

// MARK: - TransportHomePresenter

final class TransportHomePresenter {
    weak var viewController: TransportHomeDisplayLogic?
}

// MARK: - TransportHomePresentationLogic

extension TransportHomePresenter: TransportHomePresentationLogic {
    
    func present(_ response: TransportHome.Response) {
        switch response {
        case let .ridePrice(value):
            if let priceText = Formatter.balanceFormatter.string(from: .init(value: value)) {
                viewController?.display(TransportHome.ViewModel.RidePrice(text: priceText))
            }
        case let .superPayBalance(value):
            if let balanceText = Formatter.balanceFormatter.string(from: .init(value: value)) {
                viewController?.display(TransportHome.ViewModel.SuperPayBalance(text: balanceText))
            }
        }
    }
}

// MARK: - TransportHomeDisplayLogic definition

protocol TransportHomeDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: TransportHome.ViewModel.RidePrice)
    func display(_ viewModel: TransportHome.ViewModel.SuperPayBalance)
}
