//
//  TransportHomeRouter.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/28.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import Topup
import TransportHome
import CleanSwiftUtil

// MARK: - TransportHomeRouter

final class TransportHomeRouter: NSObject {
    weak var viewController: TopupBaseViewControllable?
    private let topupBuildable: TopupBuildingLogic
    private var topupRouting: ViewlessInteracting?
    
    /// 자유롭게 다른 scene builder 추가하기 (Freely add builders of different scenes)
    init(
        viewController: TopupBaseViewControllable,
        topupBuildable: TopupBuildingLogic
    ) {
        self.viewController = viewController
        self.topupBuildable = topupBuildable
    }
}

// MARK: - TransportHomeRoutingLogic

extension TransportHomeRouter: TransportHomeRoutingLogic {
    func attachTopup(listener: TopupListener) {
        guard
            nil == topupRouting,
            let viewController = viewController
        else { return }
        
        let destination = topupBuildable.build(
            withListener: listener,
            topupBaseViewController: viewController
        )
        
        topupRouting = destination
        
        destination.activate()
    }
    
    func detachTopup() {
        guard nil != topupRouting else { return }
        
        topupRouting?.deactivate()
        topupRouting = nil
    }
}
