//
//  AppHomeModels.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/28.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AppHome {
    enum Request {
        struct OnLoad {}
        struct OnWidget {
            let kind: WidgetKind
        }
    }
    
    enum Response: Equatable {
        case list([WidgetKind])
    }
    
    enum ViewModel {
        struct List {
            let items: [Widget]
        }
        
        struct Widget {
            let imageName: String
            let title: String
            let kind: WidgetKind
        }
    }
}
