//
//  AppHomePresenter.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/28.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - AppHomePresenter

final class AppHomePresenter {
    weak var viewController: AppHomeDisplayLogic?
}

// MARK: - AppHomePresentationLogic

extension AppHomePresenter: AppHomePresentationLogic {
    
    func present(_ response: AppHome.Response) {
        switch response {
        case let .list(kinds):
            var items = [AppHome.ViewModel.Widget]()
            
            for kind in kinds {
                switch kind {
                case .car:
                    items.append(
                        .init(
                            imageName: "car",
                            title: "슈퍼택시",
                            kind: kind
                        )
                    )
                case .cart:
                    items.append(
                        .init(
                            imageName: "cart",
                            title: "슈퍼마트",
                            kind: kind
                        )
                    )
                }
            }
            viewController?.display(AppHome.ViewModel.List(items: items))
        }
    }
}

// MARK: - AppHomeDisplayLogic definition

protocol AppHomeDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: AppHome.ViewModel.List)
}
