//
//  AppHomeBuilder.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/28.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import FinanceRepository
import TransportHome
import CleanSwiftUtil

// MARK: - AppHomeBuilder

public final class AppHomeBuilder: Builder<AppHomeDependency> {

}

// MARK: - AppHomeBuildingLogic

extension AppHomeBuilder: AppHomeBuildingLogic {
    public func build(withListener listener: AppHomeListener) -> Destination {
        let viewController = AppHomeViewController()
        let interactor = AppHomeInteractor(worker: AppHomeWorker(), listener: listener)
        let presenter = AppHomePresenter()
        let router = AppHomeRouter(
            viewController: viewController,
            transportHomeBuildable: dependency.transportHomeBuildable
        )
        viewController.interactor = interactor
        interactor.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController

        return viewController
    }

}

// MARK: - AppHomeBuildingLogic definition

public protocol AppHomeBuildingLogic {
    typealias Destination = UIViewController
    /// 자유롭게 매개변수 추가하기 (Add parameters freely)
    func build(withListener listener: AppHomeListener) -> Destination
}

// MARK: - AppHomeDependency

public protocol AppHomeDependency: Dependency {
    var superPayRepository: SuperPayRepositoryAvailable { get }
    var cardOnFileRepository: CardOnFileRepositoryAvailable { get }
    var transportHomeBuildable: TransportHomeBuildingLogic{ get }
}

// MARK: - AppHomeComponent

final class AppHomeComponent: Component<AppHomeDependency> {
    var cardOnFileRepository: CardOnFileRepositoryAvailable { dependency.cardOnFileRepository }
    var superPayRepository: SuperPayRepositoryAvailable { dependency.superPayRepository }
    var transportHomeBuildable: TransportHomeBuildingLogic { dependency.transportHomeBuildable }
}
