//
//  AddPaymentMethodViewController.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/02/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import SuperUI
import SuperUI

// MARK: - AddPaymentMethodViewController

final class AddPaymentMethodViewController: UIViewController {
    var interactor: AddPaymentMethodRequestLogic?
    
    private lazy var cardNumberTextField: UITextField = {
        let view = makeTextField()
        view.placeholder = "카드 번호"
        return view
    }()
    
    private lazy var securityTextField: UITextField = {
        let view = makeTextField()
        view.placeholder = "CVC"
        return view
    }()
    
    private lazy var expirationTextField: UITextField = {
        let view = makeTextField()
        view.placeholder = "유효기간"
        return view
    }()
    
    private lazy var stackView: UIStackView = {
        let view = UIStackView()
        view.translatesAutoresizingMaskIntoConstraints = false
        view.axis = .horizontal
        view.alignment = .center
        view.distribution = .fillEqually
        view.spacing = 14
        return view
    }()
    
    private lazy var addCardButton: UIButton = {
        let view = UIButton()
        view.translatesAutoresizingMaskIntoConstraints = false
        view.roundCorners()
        view.backgroundColor = .primaryRed
        view.setTitle("추가하기", for: .normal)
        view.addTarget(self, action: #selector(didTapAddCard), for: .touchUpInside)
        return view
    }()
    
    init(closeButtonType: DismissButtonType) {
        super.init(nibName: nil, bundle: nil)
        
        setupViews()
        setupNavigationItem(with: closeButtonType, target: self, action: #selector(didTapClose))
        
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        
        setupViews()
        setupNavigationItem(with: .close, target: self, action: #selector(didTapClose))
    }
    
}

// MARK: - private

extension AddPaymentMethodViewController {
    private func setupViews() {
        title = "카드 추가"
        
        view.backgroundColor = .backgroundColor
        view.addSubview(cardNumberTextField)
        view.addSubview(stackView)
        view.addSubview(addCardButton)
        stackView.addArrangedSubview(securityTextField)
        stackView.addArrangedSubview(expirationTextField)
        
        NSLayoutConstraint.activate([
            cardNumberTextField.topAnchor.constraint(equalTo: view.topAnchor, constant: 40),
            cardNumberTextField.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 40),
            cardNumberTextField.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -40),
            cardNumberTextField.bottomAnchor.constraint(equalTo: stackView.topAnchor, constant: -20),
            cardNumberTextField.heightAnchor.constraint(equalToConstant: 60),
            
            stackView.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 40),
            stackView.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -40),
            stackView.bottomAnchor.constraint(equalTo: addCardButton.topAnchor, constant: -20),
            securityTextField.heightAnchor.constraint(equalToConstant: 60),
            expirationTextField.heightAnchor.constraint(equalToConstant: 60),
            
            addCardButton.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 40),
            addCardButton.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -40),
            addCardButton.heightAnchor.constraint(equalToConstant: 60),
        ])
    }
    
    private func makeTextField() -> UITextField {
        let view = UITextField()
        view.translatesAutoresizingMaskIntoConstraints = false
        view.backgroundColor = .white
        view.borderStyle = .roundedRect
        view.keyboardType = .numberPad
        return view
    }
    
    @objc
    private func didTapAddCard() {
        if
            let number = cardNumberTextField.text,
            let cvc = securityTextField.text,
            let expiry = expirationTextField.text {
            interactor?.process(AddPaymentMethod.Request.OnConfirm(number: number, cvc: cvc, expiry: expiry))
        }
    }
    
    @objc
    private func didTapClose() {
        interactor?.process(AddPaymentMethod.Request.OnClose())
    }
}

// MARK: - AddPaymentMethodDisplayLogic

extension AddPaymentMethodViewController: AddPaymentMethodDisplayLogic {}
