//
//  AddPaymentMethodModels.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/02/20.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddPaymentMethod {

    enum Request {
        struct OnClose {}
        struct OnConfirm {
            let number: String
            let cvc: String
            let expiry: String
        }
    }
    
    enum Response: Equatable {}
    
    enum ViewModel {}
}
