//
//  FinanceHomePresenter.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/27.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - FinanceHomePresenter

final class FinanceHomePresenter {
    weak var viewController: FinanceHomeDisplayLogic?
}

// MARK: - FinanceHomePresentationLogic

extension FinanceHomePresenter: FinanceHomePresentationLogic {
    
    func present(_ response: FinanceHome.Response) {}
}

// MARK: - FinanceHomeDisplayLogic definition

protocol FinanceHomeDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
}
