//
//  AppRootPresenter.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/28.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - AppRootPresenter

final class AppRootPresenter {
    weak var viewController: AppRootDisplayLogic?
}

// MARK: - AppRootPresentationLogic

extension AppRootPresenter: AppRootPresentationLogic {
    
    func present(_ response: AppRoot.Response) {
        
    }
}

// MARK: - AppRootDisplayLogic definition

protocol AppRootDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: AppRoot.ViewModel.Something)
}
