//
//  AppRootViewController.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/28.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - AppRootViewController

final class AppRootViewController: UITabBarController {
    var interactor: AppRootRequestLogic?
    
    convenience init(
        appHomeViewController: UIViewController,
        financeHomeViewConroller: UIViewController,
        profileHomeViewConroller: UIViewController
    ) {
        self.init()
        
        viewControllers = [
            navigationController(rootViewController: appHomeViewController),
            navigationController(rootViewController: financeHomeViewConroller),
            profileHomeViewConroller
        ]
    }
    
    init() {
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }

    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        tabBar.isTranslucent = false
        tabBar.tintColor = .black
        tabBar.backgroundColor = .white
        
        interactor?.process(AppRoot.Request.OnLoad())
    }
}

// MARK: - AppRootDisplayLogic

extension AppRootViewController: AppRootDisplayLogic {
    
    func display(_ viewModel: AppRoot.ViewModel.Something) {

    }
}

// MARK: - private

extension AppRootViewController {
    private func navigationController(rootViewController: UIViewController) -> UINavigationController {
        let navigation = UINavigationController(rootViewController: rootViewController)
        navigation.navigationBar.isTranslucent = false
        navigation.navigationBar.backgroundColor = .white
        navigation.navigationBar.scrollEdgeAppearance = navigation.navigationBar.standardAppearance
        return navigation
    }
}
