//
//  EnterAmountModels.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/27.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import FinanceEntity

enum EnterAmount {

    enum Request {
        struct OnLoad {}
        struct OnClose {}
        struct OnTopup {
            let amount: Double
        }
        struct OnAddPaymentMethod {}
    }
    
    enum Response: Equatable {
        case selectedPaymentMethod(PaymentMethod)
        case loadingIndicator(show: Bool)
    }
    
    enum ViewModel {
        struct SelectedPaymentMethod {
            let image: UIImage?
            let name: String
            
            init(_ paymentMethod: PaymentMethod) {
                image = UIColor(hex: paymentMethod.color).flatMap { UIImage(color: $0) }
                name = "\(paymentMethod.name) \(paymentMethod.digits)"
            }
        }
        
        struct LoadingIndicator {
            let show: Bool
        }
    }
}
