//
//  EnterAmountPresenter.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/27.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - EnterAmountPresenter

final class EnterAmountPresenter {
    weak var viewController: EnterAmountDisplayLogic?
}

// MARK: - EnterAmountPresentationLogic

extension EnterAmountPresenter: EnterAmountPresentationLogic {
    func present(_ response: EnterAmount.Response) {
        switch response {
        case let .loadingIndicator(show):
            viewController?.display(EnterAmount.ViewModel.LoadingIndicator(show: show))
        case let .selectedPaymentMethod(paymentMethod):
            let viewModel = EnterAmount.ViewModel.SelectedPaymentMethod(paymentMethod)
            viewController?.display(viewModel)
        }
    }
}

// MARK: - EnterAmountDisplayLogic definition

protocol EnterAmountDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: EnterAmount.ViewModel.SelectedPaymentMethod)
    func display(_ viewModel: EnterAmount.ViewModel.LoadingIndicator)
}
