//
//  ProfileHomePresenter.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/28.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ProfileHomePresenter

final class ProfileHomePresenter {
    weak var viewController: ProfileHomeDisplayLogic?
}

// MARK: - ProfileHomePresentationLogic

extension ProfileHomePresenter: ProfileHomePresentationLogic {
    
    func present(_ response: ProfileHome.Response) {
        
    }
}

// MARK: - ProfileHomeDisplayLogic definition

protocol ProfileHomeDisplayLogic: AnyObject {
    /// 외부매개변수는 제외하기
    func display(_ viewModel: ProfileHome.ViewModel.Something)
}
