//
//  ProfileHomeViewController.swift
//  MiniSuperApp
//
//  Created by 정국희 on 2022/03/28.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - ProfileHomeViewController

final class ProfileHomeViewController: UIViewController {
    var interactor: ProfileHomeRequestLogic?

    // MARK: - View lifecycle
    
    init() {
        super.init(nibName: nil, bundle: nil)
        
        tabBarItem = UITabBarItem(title: "프로필", image: UIImage(systemName: "person"), selectedImage: UIImage(systemName: "person.fill"))
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        
        tabBarItem = UITabBarItem(title: "프로필", image: UIImage(systemName: "person"), selectedImage: UIImage(systemName: "person.fill"))
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
        interactor?.process(ProfileHome.Request.OnLoad())
    }
    
    private let label: UILabel = {
        let label = UILabel()
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()
    
    func setupViews() {
        label.text = "Profile Home"
        view.backgroundColor = .systemTeal
        view.addSubview(label)
        NSLayoutConstraint.activate([
            label.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            label.centerYAnchor.constraint(equalTo: view.centerYAnchor)
    ])
    }
}

// MARK: - ProfileHomeDisplayLogic

extension ProfileHomeViewController: ProfileHomeDisplayLogic {
    
    func display(_ viewModel: ProfileHome.ViewModel.Something) {

    }
}
